name: CI+CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # yarn install
    - name: Install dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test # yarn test
    - name: Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build # yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
